/** Curated 1GameHub games shown in the Fishing category (lobby order). First 25 available titles. */
export const ONEGAMEHUB_FISHING_GAMES = [
  { gameid: 'kagaming2-three-headed-dragon', title: 'Three Headed Dragon' },
  { gameid: 'kagaming2-GoldenFishHunter', title: 'Golden Fish Hunter' },
  { gameid: 'kagaming2-KAFishParty', title: 'KA Fish Party' },
  { gameid: 'kagaming2-space-cowboy', title: 'Space Cowboy' },
  { gameid: 'kagaming2-alter-world', title: 'Alter World' },
  { gameid: 'kagaming2-ocean-princess', title: 'Ocean Princess' },
  { gameid: 'kagaming2-4-dragon-kings', title: '4 Dragon Kings' },
  { gameid: 'kagaming2-DeepFishing', title: 'Deep Fishing' },
  { gameid: 'kagaming2-OctopusLegend', title: 'Octopus Legend' },
  { gameid: 'kagaming2-LuckyFish', title: 'Lucky Fish' },
  { gameid: 'kagaming2-GoldenCrab', title: 'Golden Crab' },
  { gameid: 'kagaming2-GoGoFishing', title: 'Go Go Fishing' },
  { gameid: 'kagaming2-ZodiacHunting', title: 'Zodiac Hunting' },
  { gameid: 'kagaming2-go-go-magic-dog', title: 'Go Go Magic Dog' },
  { gameid: 'kagaming2-DragonBoom', title: 'Dragon Boom' },
  { gameid: 'spadegaming-fishing-god', title: 'Fishing God' },
  { gameid: 'spadegaming-fishing-war', title: 'Fishing War' },
  { gameid: 'spadegaming-fishing-legend', title: 'Fishing Legend' },
  { gameid: 'funkygames-captain-money', title: 'Captain Money' },
  { gameid: 'funkygames-inferno-sea', title: 'Inferno Sea' },
  { gameid: 'kagaming2-AbyssDimension', title: 'Abyss Dimension' },
  { gameid: 'kagaming2-AlienAssault', title: 'Alien Assault' },
  { gameid: 'kagaming2-animal-fishing', title: 'Animal Fishing' },
  { gameid: 'kagaming2-AquaDominion', title: 'Aqua Dominion' },
  { gameid: 'kagaming2-AttackOnCrabs', title: 'Attack on Crabs' },
];
