/** Curated 1GameHub games shown in the Slots category (lobby order). */
export const ONEGAMEHUB_SLOTS_GAMES = [
  { gameid: 'kagaming2-bonus-mania', title: 'Bonus Mania' },
  { gameid: 'kagaming2-bonus-mania-deluxe', title: 'Bonus Mania Deluxe' },
  { gameid: 'kagaming2-BonusManiaPlinko', title: 'Bonus Mania Plinko' },
  { gameid: 'kagaming2-IrishCoins', title: 'Irish Coins Lock 2 Spin' },
  { gameid: 'kagaming2-supershot', title: 'SuperShot' },
  { gameid: 'kagaming2-flaming-7s', title: "Flaming 7's" },
  { gameid: 'kagaming2-CashComing', title: 'Cash Coming' },
  { gameid: 'kagaming2-treasure-bowl', title: 'Treasure Bowl' },
  { gameid: 'kagaming2-HotCoin', title: 'Hot Coin' },
  { gameid: 'kagaming2-christmas-candy', title: 'Christmas Candy' },
  { gameid: 'kagaming2-monkey-maniac', title: 'Monkey Maniac' },
  { gameid: 'kagaming2-FlamingMonkClassic', title: 'Flaming Monkey Classic' },
  { gameid: 'kagaming2-super-bonus-mania', title: 'Super Bonus Mania' },
  { gameid: 'kagaming2-BlazingBuffalo', title: 'Blazing Buffalo' },
  { gameid: 'kagaming2-triple-dragons', title: 'Triple Dragons' },
  { gameid: 'kagaming2-BlazingCircus', title: 'Blazing Circus' },
  { gameid: 'kagaming2-KingOfTheGodZeusLock2Spin', title: 'King of the God Zeus Lock 2 Spin' },
  { gameid: 'kagaming2-joker-fruit', title: 'Joker Fruit' },
  { gameid: 'kagaming2-SuperBox', title: 'Super Box' },
  { gameid: 'kagaming2-wildchristmasfusionreels', title: 'Wild Christmas Fusion Reels' },
  { gameid: 'kagaming2-super-keno', title: 'Super Keno' },
  { gameid: 'kagaming2-OlympusGods', title: 'Olympus Gods' },
  { gameid: 'kagaming2-supershot-2', title: 'SuperShot 2' },
  { gameid: 'kagaming2-777-vegas', title: '777 Vegas' },
  { gameid: 'kagaming2-LuckyStar', title: 'Lucky Star' },
  { gameid: 'kagaming2-ThreeMonkeys', title: '3x Monkeys' },
  { gameid: 'kagaming2-golden-bull', title: 'Golden Bull' },
  { gameid: 'kagaming2-hu-yeh', title: 'Hu Yeh' },
  { gameid: 'kagaming2-diamond-power', title: 'Diamond Power' },
  { gameid: 'kagaming2-hip-hop-pigeon', title: 'Hip Hop Pigeon' },
  { gameid: 'kagaming2-MissJoker', title: 'Miss Joker' },
  { gameid: 'kagaming2-SkeletonParty', title: 'Skeleton Party' },
  { gameid: 'kagaming2-king-of-dragon', title: 'King of Dragon' },
  { gameid: 'kagaming2-lightning-storm', title: 'Lightning Storm' },
  { gameid: 'kagaming2-the-gingerbread-land', title: 'The Gingerbread Land' },
  { gameid: 'kagaming2-golden-fish', title: 'Golden Fish' },
  { gameid: 'kagaming2-BigCatch', title: 'Big Catch Lock 2 Spin' },
  { gameid: 'kagaming2-quadruple-dragons', title: 'Quadruple Dragons' },
  { gameid: 'kagaming2-dragon-ball', title: 'Dragon Ball' },
  { gameid: 'kagaming2-vampires-tale', title: "Vampire's Tale" },
];
