/** Curated 1GameHub Instant Win games (lobby order). Only IDs present in the live catalog. */
export const ONEGAMEHUB_INSTANT_WIN_GAMES = [
  { gameid: 'bgaming-OpenIt', title: 'Open It!' },
  { gameid: 'bgaming-Aviamasters', title: 'Aviamasters' },
  { gameid: 'bgaming-BalloonMania', title: 'Balloon Mania' },
  { gameid: 'bgaming-Plinko2Halloween', title: 'Plinko 2 Halloween' },
  { gameid: 'bgaming-SpaceXY', title: 'Space XY' },
  { gameid: 'bgaming-Plinko2', title: 'Plinko 2' },
  { gameid: 'bgaming-PlinkoXY', title: 'Plinko XY' },
  { gameid: 'bgaming-GiftX', title: 'Gift X' },
  { gameid: 'bgaming-FortuneSpin', title: 'Fortune Spin' },
  { gameid: 'bgaming-FishingClub', title: 'Fishing Club' },
  { gameid: 'bgaming-AviamastersXmas', title: 'Aviamasters X-mas' },
  { gameid: 'bgaming-Plinko', title: 'Plinko' },
  { gameid: 'bgaming-GoldenPinataHoldAndWin', title: 'Golden Pinata' },
  { gameid: 'bgaming-FootballPlinko', title: 'Football Plinko' },
  { gameid: 'bgaming-WinterFishingClub', title: 'Winter Fishing' },
  { gameid: 'bgaming-MineGems', title: 'Mine Gems' },
  { gameid: 'bgaming-PenaltyDuel', title: 'Penalty Duel' },
  { gameid: 'bgaming-MinesweeperXY', title: 'Minesweeper XY' },
  { gameid: 'bgaming-Limbo', title: 'Limbo XY' },
  { gameid: 'bgaming-RetroTrader', title: 'Retro Trader' },
  { gameid: 'bgaming-Minesweeper', title: 'Minesweeper' },
  { gameid: 'bgaming-StreetPower', title: 'Street Power' },
  { gameid: 'bgaming-HeadsTails', title: 'Heads and Tails' },
  { gameid: 'bgaming-EasterPlinko', title: 'Easter Plinko' },
  { gameid: 'bgaming-RocketDiceXY', title: 'Rocket Dice XY' },
];
