/** Curated 1GameHub games shown in the Table Games category (lobby order). */
export const ONEGAMEHUB_TABLE_GAMES = [
  { gameid: 'kagaming2-Win3Cards', title: 'Win 3 Cards' },
  { gameid: 'kagaming2-BonusPoker', title: 'Bonus Poker' },
  { gameid: 'kagaming2-LuckyVideoPoker', title: 'Lucky Video Poker' },
  { gameid: 'kagaming2-super-video-poker', title: 'Super Video Poker' },
  { gameid: 'kagaming2-AcesAndEights', title: 'Aces and Eights' },
  { gameid: 'kagaming2-HiLo', title: 'HiLo' },
  { gameid: 'kagaming2-DragonGatePoker', title: 'Dragon Gate Poker' },
  { gameid: 'kagaming2-TeenPatti2020', title: 'Teen Patti 20-20' },
  { gameid: 'kagaming2-BauCua', title: 'Bau Cua' },
  { gameid: 'kagaming2-Super7', title: 'Super 7' },
  { gameid: 'kagaming2-AmericanRoulette', title: 'American Roulette' },
  { gameid: 'kagaming2-BoostRoulette', title: 'Boost Roulette' },
  { gameid: 'kagaming2-FrenchRoulette', title: 'French Roulette' },
  { gameid: 'kagaming2-DozenRoulette', title: 'Dozen Roulette' },
  { gameid: 'kagaming2-RouletteDoubleWin', title: 'Roulette Double Win' },
  { gameid: 'kagaming2-DragonTiger', title: 'Dragon Tiger' },
  { gameid: 'kagaming2-MegaRoulette', title: 'Mega Roulette' },
  { gameid: 'kagaming2-AndarBahar', title: 'Andar Bahar' },
  { gameid: 'kagaming2-PokDeng', title: 'Pok Deng' },
  { gameid: 'kagaming2-blazingheatroulette', title: 'Blazing Heat Roulette' },
  { gameid: 'kagaming2-PhilosopherRoulette', title: "Philosopher's Roulette" },
];
