/** Ranked popular slot titles used to order Scorpio slots in the lobby. */
export const SCORPIO_POPULAR_SLOT_NAMES = [
  "Sweet Bonanza",
  "Gates of Olympus",
  "Big Bass Splash",
  "Big Bass Bonanza",
  "Sugar Rush",
  "Great Rhino Megaways",
  "Wolf Gold",
  "The Dog House",
  "John Hunter and the Tomb of the Scarab Queen",
  "Chilli Heat Megaways",
  "Cowboy Coins",
  "Release the Kraken",
  "Gold Train",
  "Devilicious",
  "Fortune Gems",
  "Super Ace",
  "Boxing King",
  "Lucky Coming",
  "Golden Empire",
  "Charge Buffalo",
  "Wild Ace",
  "Hot Hot Fruit",
  "Mystic Fortune Deluxe",
  "Koi Gate",
  "Laughing Buddha",
  "Space Goonz",
  "Mighty Medusa",
  "Gold Rush",
  "Mahjong Ways",
  "Dragon Hatch",
  "Fortune Tiger",
  "Fortune Mouse",
  "Fortune Rabbit",
  "The Dog House Megaways",
  "Buffalo King Megaways",
  "Buffalo King",
  "Great Rhino",
  "Great Rhino Deluxe",
  "Monkey Warrior",
  "Diamond Strike",
  "Wild West Gold",
  "Tree of Riches",
  "Cash Elevator",
  "Panda's Fortune",
  "Dance Party",
  "5 Lions Gold",
  "5 Lions Megaways",
  "5 Lions",
  "Caishen's Cash",
  "Hot to Burn",
  "Fruit Party 2",
  "Hot Fiesta",
  "Juicy Fruits",
  "Da Vinci's Treasure",
  "Curse of the Werewolf Megaways",
  "Hercules and Pegasus",
  "Gold Party",
  "Magician's Secrets",
  "Caishen's Gold",
  "Mustang Gold",
  "Emerald King Rainbow Road",
  "Madame Destiny Megaways",
  "Sweet Bonanza Xmas",
  "Pirate Gold Deluxe",
  "Book Of Kingdoms",
  "Congo Cash",
  "Dragon Kingdom - Eyes of Fire",
  "Rise of Samurai",
  "Voodoo Magic",
  "Lucky New Year",
  "Yum Yum Powerways",
  "Fruit Party",
  "Madame Destiny",
  "5 Lions Dance",
  "888 Dragons",
  "Aztec Gems",
  "Aztec Gems Deluxe",
  "Candy Village",
  "Chilli Heat",
  "Dragon Kingdom",
  "Emerald King",
  "Fire Strike",
  "Floating Dragon",
  "Gems Bonanza",
  "Journey to the West",
  "Master Chen's Fortune",
  "Star Pirates Code",
  "Starlight Princess",
  "Wild Walker",
  "Wild Wild Riches",
  "Cash Patrol",
  "Colossal Cash Zone",
  "Barn Festival",
  "Big Bass Bonanza Megaways",
  "Wild West Gold Megaways",
  "The Great Stick-up",
  "Fire Strike 2",
  "Drill That Gold",
  "Bomb Bonanza",
  "Book of Golden Sands",
  "Gates of Gatot Kaca",
  "Wild Wild Bananas",
  "Wild Wild Riches Megaways",
  "Rabbit Garden",
  "The Dog House Multihold",
  "Zeus vs Hades - Gods of War",
  "Big Bass Amazon Xtreme",
  "Wisdom of Athena",
  "Starlight Princess 1000",
  "Big Bass Halloween",
  "Gates of Olympus 1000",
  "Big Bass Day at the Races",
  "Sugar Rush 1000",
  "Fruity Treats",
  "Sweet Bonanza 1000",
  "Big Bass Bonanza 1000",
  "Flaming Hot",
  "Shining Crown",
  "40 Burning Hot",
  "Burning Hot",
  "20 Super Hot",
  "40 Super Hot",
  "Fortune Gods",
  "Hood vs Wolf",
  "Tree of Fortune",
  "Legend of Hou Yi",
  "Mr. Hallow-Win",
  "Prosperity Lion",
  "Ganesha Gold",
  "Journey to the Wealth",
  "Captain's Bounty",
  "Vampire's Charm",
  "Ninja vs Samurai",
  "Leprechaun Riches",
  "Gem Saviour Conquest",
  "Muay Thai Champion",
  "Caishen Wins",
  "Egypt's Book of Mystery",
  "Mahjong Ways 2",
  "Ganesha Fortune",
  "Dreams of Macau",
  "Phoenix Rises",
  "Wild Fireworks",
  "Queen Of Bounty",
  "Treasures of Aztec",
  "Lucky Neko",
  "Opera Dynasty",
  "Fortune Ox",
  "Rise of Apollo",
  "Mermaid Riches",
  "Wild Bandito",
  "Heist  Stakes",
  "Ways of the Qilin",
  "Buffalo Win",
  "Jurassic Kingdom",
  "Cocktail Nights",
  "Speed Winner",
  "Legend of Perseus",
  "Wild Coaster",
  "Prosperity Fortune Tree",
  "Alchemy Gold",
  "Songkran Splash",
  "Werewolf's Hunt",
  "Chin Shi Huang",
  "Fa Fa Fa",
  "Crazy 777",
  "Zeus",
  "Wealth Inn",
  "27 Wins",
  "Circus Brilliant",
  "Wanted Dead or a Wild",
  "Beast Below",
  "Chaos Crew",
  "Cubes 2",
  "Dork Unit",
  "40 Lucky Wilds Hot Golden Coins Link",
  "Aztec King Megaways",
  "Lucky New Year - Tiger Treasures",
  "Dragon King Hot Pots",
  "Aztec Gems Megaways",
  "100 Lucky Wilds Hot Coin Boost",
  "Panda Fortune 2",
  "Treasure Wild",
  "Rise of Samurai Megaways",
  "Aztec Treasure",
  "Hercules Son of Zeus",
  "Lucky Dragon Ball",
  "Aztec King",
  "Aztec Bonanza",
  "Bonanza Gold",
  "Cash Bonanza",
  "Dragon Hot Hold & Spin",
  "Dwarven Gold Deluxe",
  "Elemental Gems Megaways",
  "Lucky Dragons",
  "The Dragon Tiger",
  "Book of Aztec King",
  "Fire Hot 5",
  "Fire Hot 20",
  "Fire Hot 40",
  "Fire Hot 100",
  "Striking Hot 5",
  "Mammoth Gold Megaways",
  "40 Lucky King",
  "40 Lucky King Bell Link",
  "40 Lucky King Extreme Bell Link",
  "40 Lucky King VIP Bell Link",
  "40 Lucky King Extreme VIP Bell Link",
  "Dragon Tiger Luck",
  "Wild Heist Cashout",
  "Gemstones Gold",
  "Fortune Dragon",
  "Mr. Treasure's Fortune",
  "Dragon's Treasure Quest",
  "Tiger's Gold",
  "Aztec Fire",
  "Treasures of Fire: Scatter Pays",
  "Tiger Gems",
  "Aztec Fire 2",
  "Coin UP: Hot Fire",
  "Hot Fire Fruits",
  "Buffalo Power Megaways",
  "Wild Cats Fire: Hold and Win",
  "Fortune Gems 2",
  "Fortune Gems 3",
  "Lucky Fortune Cat",
  "Dragon Tiger Gate",
  "Lucky Tigers",
  "Fire777",
  "Diamond treasure",
  "Dragon's Treasure",
  "100 Power Hot Golden Coins Link",
  "100 Power Hot Golden Coins Link VIP",
  "20 Glossy Hot Golden Coins Link",
  "20 Glossy Hot Golden Coins Link (2)",
  "40 Hot & Cash",
  "40 Power Hot Golden Coins Link",
  "Golden Tiger",
  "Golden Tiger 1000",
  "Hot & Cash",
  "Lucky & Wild",
  "Lucky Hot",
  "More Lucky & Wild",
  "Burning Hot Progressive JP",
  "20 Super Hot Progressive JP",
  "Burning Hot Bell Link",
  "5 Dazzling Hot",
  "20 Super Hot Bell Link",
  "40 Super Hot Progressive JP",
  "Flaming Hot Bell Link",
  "5 Dazzling Hot Bell Link",
  "40 Burning Hot Bell Link",
  "Versailles Gold Progressive JP",
  "20 Burning Hot",
  "Hotpot",
  "Dragon Legend",
  "Hip Hop Panda",
  "Piggy Gold",
  "Double Fortune",
  "Galactic Gems",
  "Dragon Pearls: Hold and Win",
  "Scarab Riches",
  "Great Panda",
  "Aztec Sun",
  "Buffalo Power: Hold and Win",
  "15 Dragon Pearls",
  "Fortune Tree",
  "War Of Dragons",
  "Jungle King",
  "Golden Bank",
  "Golden Queen",
  "Fa Cai Shen Deluxe",
  "Hot Hot Halloween",
  "Colossal Gems",
  "Wild Trucks",
  "Lucky Lucky",
  "Ways Of Fortune",
  "Panda Panda",
  "Fire Rooster",
  "Roman Empire",
  "Striker WILD",
  "Dragon Koi",
  "King of Atlantis",
  "Hot Pinatas",
  "King Kong Shake",
  "LuckyBoxes",
  "TreasureIsland",
  "Pharaoh's Gold",
  "2 Wild 2 Die",
  "Aztec Twist"
];
