/** Curated Slots category: GitSlotPark only, ranked by live play (12 Aug–12 Sept). */
export const SLOTS_CATEGORY_GAMES = [
  { provider: 'gitslotpark', gameid: '33', title: 'Hip Hop Panda' },
  { provider: 'gitslotpark', gameid: '104', title: 'Wild Bandito' },
  { provider: 'gitslotpark', gameid: '36', title: 'Prosperity Lion' },
  { provider: 'gitslotpark', gameid: '29', title: 'Dragon Legend' },
  { provider: 'gitslotpark', gameid: '3', title: 'Fortune Gods' },
  { provider: 'gitslotpark', gameid: '60', title: 'Leprechaun Riches' },
  { provider: 'gitslotpark', gameid: '37', title: "Santa's Gift Rush" },
  { provider: 'gitslotpark', gameid: '82', title: 'Phoenix Rises' },
  { provider: 'gitslotpark', gameid: '54', title: 'Captain Bounty' },
  { provider: 'gitslotpark', gameid: '1', title: 'Honey Trap Of Diao Chan' },
  { provider: 'gitslotpark', gameid: '83', title: 'Wild Fireworks' },
  { provider: 'gitslotpark', gameid: '7', title: 'Medusa' },
  { provider: 'gitslotpark', gameid: '1473388', title: 'Cruise Royale' },
  { provider: 'gitslotpark', gameid: '35', title: 'Mr. Hallow-Win' },
  { provider: 'gitslotpark', gameid: '25', title: 'Plushie Frenzy' },
  { provider: 'gitslotpark', gameid: '4704' },
  { provider: 'gitslotpark', gameid: '85', title: 'Ganesha Gold' },
  { provider: 'gitslotpark', gameid: '6', title: 'Medusa II' },
  { provider: 'gitslotpark', gameid: '75', title: 'Candy Burst' },
  { provider: 'gitslotpark', gameid: '108', title: 'Buffalo Win' },
  { provider: 'gitslotpark', gameid: '4528' },
  { provider: 'gitslotpark', gameid: '4516' },
  { provider: 'gitslotpark', gameid: '105', title: 'Heist Stakes' },
  { provider: 'gitslotpark', gameid: '42', title: 'Gem Saviour Sword' },
  { provider: 'gitslotpark', gameid: '48', title: 'Double Fortune' },
  { provider: 'gitslotpark', gameid: '126', title: 'Forge of Wealth' },
  { provider: 'gitslotpark', gameid: '1695365' },
  { provider: 'gitslotpark', gameid: '73', title: "Egypt's Book of Mystery" },
  { provider: 'gitslotpark', gameid: '121', title: 'Destined for Riches' },
  { provider: 'gitslotpark', gameid: '1381200' },
  { provider: 'gitslotpark', gameid: '4629' },
  { provider: 'gitslotpark', gameid: '117', title: 'Cocktail Nights' },
  { provider: 'gitslotpark', gameid: '123', title: 'Rooster Rumble' },
  { provider: 'gitslotpark', gameid: '87', title: 'Treasures of Aztec' },
  { provider: 'gitslotpark', gameid: '34', title: 'Legend of Hou Yi' }
];
