'use strict';

/** Ledger wallet jars. BONUS is stored as BSC on the wallets table. */
const WALLET_TYPES = {
  PSC: 'PSC',
  BONUS: 'BONUS',
  RSC: 'RSC'
};

const DIRECTIONS = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
};

const PRODUCT_IDS = {
  JUWA: 'JUWA',
  GAMEVAULT: 'GAMEVAULT',
  GOLDEN_DRAGON: 'GOLDEN_DRAGON',
  DIRECT: 'DIRECT',
  OTHER: 'OTHER'
};

const PRODUCT_TYPES = {
  EXTERNAL: 'EXTERNAL',
  DIRECT: 'DIRECT'
};

const EVENT_TYPES = {
  OPENING_SNAPSHOT: 'OPENING_SNAPSHOT',
  PURCHASE: 'PURCHASE',
  PACKAGE_BONUS: 'PACKAGE_BONUS',
  WELCOME_BONUS: 'WELCOME_BONUS',
  SPIN_BONUS: 'SPIN_BONUS',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  COINBACK: 'COINBACK',
  DAILY_BONUS: 'DAILY_BONUS',
  VIP_BONUS: 'VIP_BONUS',
  BONUS_CODE: 'BONUS_CODE',
  MANUAL_CREDIT: 'MANUAL_CREDIT',
  MANUAL_DEBIT: 'MANUAL_DEBIT',
  MANUAL_BONUS: 'MANUAL_BONUS',
  ADJUSTMENT_CREDIT: 'ADJUSTMENT_CREDIT',
  ADJUSTMENT_DEBIT: 'ADJUSTMENT_DEBIT',
  USED_JUWA: 'USED_JUWA',
  USED_GAMEVAULT: 'USED_GAMEVAULT',
  USED_GOLDEN_DRAGON: 'USED_GOLDEN_DRAGON',
  USED_DIRECT: 'USED_DIRECT',
  USED_OTHER: 'USED_OTHER',
  WIN_JUWA: 'WIN_JUWA',
  WIN_GAMEVAULT: 'WIN_GAMEVAULT',
  WIN_GOLDEN_DRAGON: 'WIN_GOLDEN_DRAGON',
  WIN_DIRECT: 'WIN_DIRECT',
  WIN_OTHER: 'WIN_OTHER',
  REFUND: 'REFUND',
  WITHDRAWAL: 'WITHDRAWAL',
  EXPIRED: 'EXPIRED',
  VOIDED: 'VOIDED',
  CASHOUT_CAP_VOID: 'CASHOUT_CAP_VOID',
  NEVER_DEPOSITED_CLEAR: 'NEVER_DEPOSITED_CLEAR',
  UNCLASSIFIED: 'UNCLASSIFIED'
};

const BONUS_TYPES = {
  PACKAGE_BONUS: 'PACKAGE_BONUS',
  WELCOME_BONUS: 'WELCOME_BONUS',
  SPIN_BONUS: 'SPIN_BONUS',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  COINBACK: 'COINBACK',
  DAILY_BONUS: 'DAILY_BONUS',
  VIP_BONUS: 'VIP_BONUS',
  BONUS_CODE: 'BONUS_CODE',
  MANUAL_BONUS: 'MANUAL_BONUS',
  OTHER_BONUS: 'OTHER_BONUS',
  LEGACY_BALANCE: 'LEGACY_BALANCE'
};

const EXCESS_WIN_ACTIONS = {
  VOID: 'void',
  KEEP: 'keep',
  CONVERT: 'convert'
};

const CURRENCY_TO_WALLET = {
  PSC: WALLET_TYPES.PSC,
  BSC: WALLET_TYPES.BONUS,
  RSC: WALLET_TYPES.RSC,
  SC: WALLET_TYPES.PSC
};

const WALLET_TO_CURRENCY = {
  [WALLET_TYPES.PSC]: 'PSC',
  [WALLET_TYPES.BONUS]: 'BSC',
  [WALLET_TYPES.RSC]: 'RSC'
};

const USED_EVENT_BY_PRODUCT = {
  [PRODUCT_IDS.JUWA]: EVENT_TYPES.USED_JUWA,
  [PRODUCT_IDS.GAMEVAULT]: EVENT_TYPES.USED_GAMEVAULT,
  [PRODUCT_IDS.GOLDEN_DRAGON]: EVENT_TYPES.USED_GOLDEN_DRAGON,
  [PRODUCT_IDS.DIRECT]: EVENT_TYPES.USED_DIRECT,
  [PRODUCT_IDS.OTHER]: EVENT_TYPES.USED_OTHER
};

const WIN_EVENT_BY_PRODUCT = {
  [PRODUCT_IDS.JUWA]: EVENT_TYPES.WIN_JUWA,
  [PRODUCT_IDS.GAMEVAULT]: EVENT_TYPES.WIN_GAMEVAULT,
  [PRODUCT_IDS.GOLDEN_DRAGON]: EVENT_TYPES.WIN_GOLDEN_DRAGON,
  [PRODUCT_IDS.DIRECT]: EVENT_TYPES.WIN_DIRECT,
  [PRODUCT_IDS.OTHER]: EVENT_TYPES.WIN_OTHER
};

const BONUS_ISSUED_GROUPS = {
  PACKAGE_BONUS: [EVENT_TYPES.PACKAGE_BONUS],
  WELCOME_BONUS: [EVENT_TYPES.WELCOME_BONUS],
  SPIN_BONUS: [EVENT_TYPES.SPIN_BONUS],
  REFERRAL_BONUS: [EVENT_TYPES.REFERRAL_BONUS],
  COINBACK: [EVENT_TYPES.COINBACK],
  OTHER_BONUS: [
    EVENT_TYPES.DAILY_BONUS,
    EVENT_TYPES.VIP_BONUS,
    EVENT_TYPES.BONUS_CODE,
    EVENT_TYPES.MANUAL_BONUS,
    EVENT_TYPES.OTHER_BONUS,
    EVENT_TYPES.UNCLASSIFIED,
    EVENT_TYPES.ADJUSTMENT_CREDIT,
    EVENT_TYPES.REFUND
  ]
};

module.exports = {
  WALLET_TYPES,
  DIRECTIONS,
  PRODUCT_IDS,
  PRODUCT_TYPES,
  EVENT_TYPES,
  BONUS_TYPES,
  EXCESS_WIN_ACTIONS,
  CURRENCY_TO_WALLET,
  WALLET_TO_CURRENCY,
  USED_EVENT_BY_PRODUCT,
  WIN_EVENT_BY_PRODUCT,
  BONUS_ISSUED_GROUPS
};
